apiVersion: v2
name: s3webui
description: Web UI for multiple S3 endpoint
type: application
version: 1.3.4
appVersion: "1.3.4"
dependencies:
  - name: s3webui
    repository: https://charts.wenisch.tech
    version: 1.3.4
    condition: s3webui.enabled
