s3webui:
  enabled: true
  fullnameOverride: s3webui
  podSecurityContext: ~
  persistence:
    enabled: true
  ingress:
    enabled: true
    className: ""
    annotations: {}
    hosts:
      - host: s3webui.apps.ocpbm02s2.cores.r2.pi2.minint.fr
        paths:
          - path: /
            pathType: Prefix
    tls: []
  env:
    ADMIN_EMAIL: "admin@numerique-interieur.com"

  # Secret are override by vso
  secrets:
    ADMIN_PASSWORD: "Tmp-Admin-9xK7!pQ2#vL8"
    APP_ENCRYPTION_KEY: "bW9ja19lbmNyeXB0aW9uX2tleV8zMmJ5dGVzX2xvbmc="
    SPRING_DATASOURCE_PASSWORD: "Tmp-Db-4mN8!zR6@qW2"

vault:
  enabled: true
  authRef: vault-auth
  secretMount: s3webui
  secretType: kv-v2
  refreshAfter: 15m
