s3webui:
  enabled: true
  fullnameOverride: s3webui
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi
  podSecurityContext: ~
  persistence:
    enabled: true
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: self-signed-ca
    hosts:
      - host: s3webui.apps.ocpbm02s2.cores.r2.pi2.minint.fr
        paths:
          - path: /
            pathType: Prefix
    tls:
    - hosts:
      - s3webui.apps.ocpbm02s2.cores.r2.pi2.minint.fr
      secretName: s3webui-tls
  env:
    ADMIN_EMAIL: "admin@numerique-interieur.com"

  # Secret are override by vso
  secrets: {}
  existingSecrets:
    - s3webui

vault:
  enabled: true
  authRef: vault-auth
  secretMount: s3webui
  secretType: kv-v2
  refreshAfter: 15m
